# Generated by Django 4.2.9 on 2024-12-13 06:23

from django.db import migrations
import trix_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_category_remove_blogpost_snippet_blogpost_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=trix_editor.fields.TrixEditorField(),
        ),
    ]
