# Generated by Django 5.1.4 on 2024-12-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_rename_image_blogpost_cover_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="reading_time",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
