# Generated by Django 5.1.4 on 2024-12-19 05:07

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.CharField(max_length=10, unique=True)),
                ("title", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "course_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/course_images/"
                    ),
                ),
                (
                    "course_image_alt",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=8, null=True),
                ),
                ("short_description", ckeditor.fields.RichTextField(blank=True)),
                ("long_description", ckeditor.fields.RichTextField(blank=True)),
                ("learning_outcomes", ckeditor.fields.RichTextField(blank=True)),
                ("pre_requisites", ckeditor.fields.RichTextField(blank=True)),
                ("who_is_the_course_for", ckeditor.fields.RichTextField(blank=True)),
                ("language", models.CharField(default="English", max_length=50)),
                ("preview_video", models.URLField(blank=True, null=True)),
                ("course_content", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status_live", models.BooleanField(default=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
