# Generated by Django 5.1.4 on 2024-12-19 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_chapter_lesson"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="slug",
            new_name="course_url",
        ),
    ]
